module.exports = {
	fr: {
		location: "Lieu :",
		online: "En ligne",
		hostedBy: "Présenté par",
		startTime: "Heure de début de l'événement",
		endTime: "Heure de fin de l'événement",
		eventDate: "Date de l'événement",
		language: "Langue de la présentation",
		audience: "Audience",
		eventLocation: "Lieu de l'événement",
		learningActivitiesHeading: "Occasions d'apprentissage",
		requestAvailable: "Disponible sur demande",
		upcomingActivities: "Activités d'apprentissage à venir",
		noUpcomingActivities: "Aucune activité d'apprentissage à venir",
		scheduledActivities: "Activités d'apprentissage de l'AATIA",
		noScheduledActivities: "Aucune activité d'apprentissage prévue",
		pastActivities: "Activités d'apprentissage passées",
		eventDetails: {
			headingText: "Détails de l'événement",
			timeText: "Heure :",
			registrationText: "Inscription :",
			signLangText: "Interprète en langue des signes :",
			signLangAvailable: "Disponible",
			platformText: "Format :",
		},
	},
	en: {
		location: "Location:",
		online: "Online",
		hostedBy: "Presented by",
		startTime: "Event start time",
		endTime: "Event end time",
		eventDate: "Event date",
		language: "Language of presentation",
		audience: "Audience",
		eventLocation: "Location",
		learningActivitiesHeading: "Learning opportunities",
		requestAvailable: "Available upon request",
		upcomingActivities: "Upcoming learning activities",
		noUpcomingActivities: "No upcoming learning activities",
		scheduledActivities: "AAACT learning activities",
		noScheduledActivities: "No scheduled learning activities",
		pastActivities: "Past learning activities",
		eventDetails: {
			headingText: "Event Details",
			timeText: "Time:",
			registrationText: "Registration:",
			signLangText: "Sign language interpreter:",
			signLangAvailable: "Available",
			platformText: "Delivery:",
		},
	},
};
