module.exports = {
	fr: {
		location: "Lieu :",
		online: "En ligne",
		hostedBy: "Présenté par",
		startTime: "Heure de début de l'événement",
		endTime: "Heure de fin de l'événement",
		eventDate: "Date de l'événement",
		language: "Langue de la présentation",
		audience: "Audience",
		eventLocation: "Lieu de l'événement",
		contactUs: "Contactez-nous pour plus d'informations sur AATIA Apprentissage à notre adresse courriel&nbsp;: ",
		emailSubject: "Courriel à propos AATIA Apprentissage : ",
		learningActivitiesHeading: "Occasions d'apprentissage",
		eventDate: "Date prévue",
		requestAvailable: "Disponible sur demande",
		upcomingActivities: "Activités d'apprentissage à venir",
		noUpcomingActivities: "Aucune activité d'apprentissage à venir",
		scheduledActivities: "Demander une session d'apprentissage privée",
		noScheduledActivities: "Aucune activité d'apprentissage prévue",
		eventDetails: {
			headingText: "Détails de l'événement",
			timeText: "Heure :",
			registrationText: "Inscription :",
			signLangText: "Interprète en langue des signes :",
			signLangAvailable: "Disponible",
			platformText: "Plate-forme :",
		},
	},
	en: {
		location: "Location:",
		online: "Online",
		hostedBy: "Presented by",
		startTime: "Event start time",
		endTime: "Event end time",
		eventDate: "Event date",
		language: "Language of presentation",
		audience: "Audience",
		eventLocation: "Location",
		contactUs: "Contact us for more information about AAACT Learning at our email: ",
		emailSubject: "Email about AAACT Learning: ",
		learningActivitiesHeading: "Learning opportunities",
		eventDate: "Scheduled date",
		requestAvailable: "Available upon request",
		upcomingActivities: "Upcoming learning activities",
		noUpcomingActivities: "No upcoming learning activities",
		scheduledActivities: "Request a private learning session",
		noScheduledActivities: "No scheduled learning activities",
		eventDetails: {
			headingText: "Event Details",
			timeText: "Time:",
			registrationText: "Registration:",
			signLangText: "Sign language interpreter:",
			signLangAvailable: "Available",
			platformText: "Platform:",
		},
	},
};
