local_backend: true

# Use DecapBridge auth
backend:
  name: git-gateway
  repo: aaact-aatia/aaact-aatia.github.io
  branch: main
  identity_url: https://auth.decapbridge.com/sites/26e21dc3-ba5e-49f2-9c2d-f1dd43f1117c
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} via DecapBridge

publish_mode: editorial_workflow

media_folder: "/public/docs" # Media files will be stored in the repo under this path
public_folder: "/docs" # The src attribute for uploaded media will begin with this path

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title (required)", name: "title", widget: "string", i18n: true }
      - { label: "Other language title", name: "otherLanguageTitle", required: false, widget: "string", i18n: true }
      - { label: "Tagline", name: "tagline", required: false, widget: "markdown", i18n: true }
      - { label: "Description (required)", name: "description", widget: "markdown", i18n: true }
      - { label: "Permalink (full path)", name: "permalink", required: false, widget: "string", i18n: true }
      - { label: "Permalink to other language (full path)", name: "otherLanguagePermalink", required: false, widget: "string", i18n: true }
      - { label: "Details (required)", name: "body", widget: "markdown",  i18n: true }

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title (required)", name: "title", widget: "string", i18n: true }
      - { label: "Other language title", name: "otherLanguageTitle", widget: "string", i18n: true }
      - { label: "Tagline", name: "tagline", widget: "markdown", i18n: true }
      - { label: "Description (required)", name: "description", widget: "markdown", i18n: true }
      - { label: "Event Date (YYYY-MM-DD) (required)", name: "eventDate", widget: "datetime", date_format: "YYYY-MM-DD", i18n: duplicate, required: false }
      - { label: "Details (required)", name: "body", widget: "markdown",  i18n: true }
