backend:
  name: github
  repo: aaact-aatia/aaact-aatia.github.io
  branch: main

publish_mode: editorial_workflow

media_folder: "/public/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Host", name: "host", widget: "string", default: "", i18n: true }
      - { label: "Language", name: "language", widget: "select", options: ["English", "French"], i18n: duplicate }
      - { label: "Online", name: "online", widget: "boolean", default: duplicate }
      - { label: "Link", name: "link", widget: "string", i18n: duplicate }
      - { label: "Link Text", name: "linkText", widget: "string", i18n: true }
      - { label: "Teams ID", name: "teamsID", required: false, widget: "string", i18n: duplicate }
      - { label: "Audience", name: "audience", widget: "select", options: ["GC Employees and Managers", "All GC employees"], i18n: duplicate }
      - { label: "Event Date", name: "eventDate", widget: "datetime", date_format: "YYYY-MM-DD", i18n: duplicate }
      - { label: "Event Start Time", name: "startTime", widget: "datetime", time_format: "HH:mm", i18n: duplicate }
      - { label: "Event End Time", name: "endTime", widget: "datetime", time_format: "HH:mm", i18n: duplicate }
      - { label: "Location", name: "location", widget: "string", default: "Microsoft Teams", i18n: duplicate }
      - { label: "Details", name: "body", widget: "markdown",  i18n: true }
